# -*- coding: utf-8 -*-
"""Shared schema exports for report and v2 analysis contracts."""

from src.stock_analysis_skill.contracts import (
    AnalysisContextMeta,
    AnalysisExecution,
    AnalysisFeatures,
    AnalysisMode,
    AnalysisOutput,
    AnalysisRequest,
    AnalysisResponse,
    BatchAnalysisRequest,
    BatchSharedOptions,
    ChecklistStatus,
    ConfidenceLevel,
    DashboardBlock,
    DashboardChecklistItem,
    DataCompleteness,
    DecisionAction,
    DecisionBlock,
    EvidenceBlock,
    IntelBlock,
    IntelNewsItem,
    Market,
    MetadataBlock,
    OutputFormat,
    OutputVerbosity,
    QuerySource,
    SelectionSource,
    StockInfo,
    StockTarget,
    TrendBlock,
    TrendStatus,
)
from src.schemas.report_schema import AnalysisReportSchema

__all__ = [
    "AnalysisContextMeta",
    "AnalysisExecution",
    "AnalysisFeatures",
    "AnalysisMode",
    "AnalysisOutput",
    "AnalysisReportSchema",
    "AnalysisRequest",
    "AnalysisResponse",
    "BatchAnalysisRequest",
    "BatchSharedOptions",
    "ChecklistStatus",
    "ConfidenceLevel",
    "DashboardBlock",
    "DashboardChecklistItem",
    "DataCompleteness",
    "DecisionAction",
    "DecisionBlock",
    "EvidenceBlock",
    "IntelBlock",
    "IntelNewsItem",
    "Market",
    "MetadataBlock",
    "OutputFormat",
    "OutputVerbosity",
    "QuerySource",
    "SelectionSource",
    "StockInfo",
    "StockTarget",
    "TrendBlock",
    "TrendStatus",
]
